### ISSUE TITLE
Add functionality to get individual match data

### ISSUE THREAD

**Issue by aamirsahmad** [qlaffont/fortnite-api#101]
Is there an EPIC Games API endpoint that serves individual match data such as 

- Date
- Kills
- Wins
- Matches
- K/D

**Comment by RobertoGraham** [comment]
Not that I've seen from any client. You could  fetch stats for a user every 3mins or so and compare to their old stats. If there's a difference of 1 game you'll have the match stats + a rough timestamp

**Comment by kinsi55** [comment]
not possible / not exposed by epic

**Comment by monkeydioude** [comment]
Does not exist
