### ISSUE TITLE
Leaderboards request not working.

### ISSUE THREAD

**Issue by Muna2242** [qlaffont/fortnite-api#102]
I received a server error from the leaderboard request, didn't got it until today. I don't know if the endpoint have been change or if it's my own problem or it's happening to everyone. Would be amazing if you could check it.

**Comment by RobertoGraham** [comment]
I'm getting it too, seems like an problem on epic games' side

`{"errorCode":"errors.com.epicgames.common.server_error","errorMessage":"Sorry an error occurred and we were unable to resolve it (tracking id: [3f4b2c85-be62-4dc6-943e-8776e12f1914])","messageVars":["3f4b2c85-be62-4dc6-943e-8776e12f1914"],"numericErrorCode":1000,"originatingService":"fortnite","intent":"prod-live","trackingId":"3f4b2c85-be62-4dc6-943e-8776e12f1914"}`

**Comment by qlaffont** [comment]
Yep if you have more info to get the leaderboard make a PR. If not i will delete this request.

**Comment by AlloGaming** [comment]
I got also the same Error: 
https://hastebin.com/hiriwowiha.json

**Comment by weeco** [comment]
How do you intend to figure that out since Epic Games implemented SSL pinning? I doubt it's an issue on Epic Games side, I rather believe they intentionally changed the request.
