### ISSUE TITLE
GetStats -> Nintendo Switch player

### ISSUE THREAD

**Issue by DatMayolein** [qlaffont/fortnite-api#103]
Hey,

is there a way to get the stats of a switch profile?

**Comment by hadouken111** [comment]
Hello, and IOS & Android  too???

**Comment by monkeydioude** [comment]
[-_-](https://github.com/Tustin/fortnite-php/issues/16)

**Comment by monkeydioude** [comment]
Anyone playing on Switch ? I tried with username found on Fortnite Switch players on reddit but did not find any info, having no certainty reddit username match those used IG :neutral_face:

**Comment by RobertoGraham** [comment]
This is the response for user "Kronosbeen" who definitely plays on Switch:
`[{"name":"br_score_pc_m0_p10","value":10554,"window":"weekly","ownerType":1},{"name":"br_score_pc_m0_p9","value":330,"window":"weekly","ownerType":1},{"name":"br_matchesplayed_pc_m0_p10","value":77,"window":"weekly","ownerType":1},{"name":"br_score_pc_m0_p2","value":5285,"window":"weekly","ownerType":1},{"name":"br_kills_pc_m0_p2","value":16,"window":"weekly","ownerType":1},{"name":"br_matchesplayed_pc_m0_p2","value":52,"window":"weekly","ownerType":1},{"name":"br_matchesplayed_pc_m0_p9","value":2,"window":"weekly","ownerType":1},{"name":"br_placetop12_pc_m0_p10","value":21,"window":"weekly","ownerType":1},{"name":"br_placetop10_pc_m0_p2","value":3,"window":"weekly","ownerType":1},{"name":"br_placetop25_pc_m0_p2","value":12,"window":"weekly","ownerType":1},{"name":"br_placetop5_pc_m0_p10","value":10,"window":"weekly","ownerType":1},{"name":"br_kills_pc_m0_p10","value":21,"window":"weekly","ownerType":1},{"name":"br_placetop6_pc_m0_p9","value":1,"window":"weekly","ownerType":1}]`

Switch Fortnite has no stats tab so it's unlikely they're available on any endpoint

**Comment by RobertoGraham** [comment]
Proof of playing on Switch:
`[{"id":"1a259630e211489598cff7bab3243457","displayName":"Kronosbeen","externalAuths":{"nintendo":{"type":"nintendo","externalAuthId":"lp1_cabc45844979457e","externalAuthIdType":"nsa_id","accountId":"1a259630e211489598cff7bab3243457","authIds":[{"id":"lp1_ed7794759f8eac07","type":"nintendo_id"},{"id":"lp1_cabc45844979457e","type":"nsa_id"}]}}}]`

**Comment by monkeydioude** [comment]
wp sir!

it's time for the famous plan "we do nothing"

**Comment by qlaffont** [comment]
Actually, We have no stat in Switch. So we need to wait.
