### ISSUE TITLE
Struggling to find my client token

### ISSUE THREAD

**Issue by tfhdevelopment** [qlaffont/fortnite-api#104]
I think i have successfully found the first,
/account/api/oauth/token (Authorization header content and remove basic)
however in the header section of fiddler im not sure if its correct as it looks a little different from yours

 /account/api/oauth/token

I've followed the steps but i cant find the second token

**Comment by monkeydioude** [comment]
(https://github.com/qlaffont/fortnite-api/issues/94)[https://github.com/qlaffont/fortnite-api/issues/94]
