### ISSUE TITLE
Season data

### ISSUE THREAD

**Issue by RayzonDE** [qlaffont/fortnite-api#106]
How can I get the season data like fortnitetracker or this api https://fortniteapi.com/docs/open/4 ?

Do someone know how the endpoint for season stats is?

**Comment by RobertoGraham** [comment]
It's counter-intuitive but if you change `alltime` to `weekly` here you will get stats for the current season only

**Comment by RobertoGraham** [comment]
Probably some EpicGames tech debt that they aren't arsed enough to address

**Comment by RayzonDE** [comment]
Can I get the alltime and weekly data in one request?

**Comment by qlaffont** [comment]
@RobertoGraham you can make a pull request if you want ;). @RayzonDE no, because it's 2 HTTP requests.
