### ISSUE TITLE
Leaderboars request error

### ISSUE THREAD

**Issue by JordiFerrerB** [qlaffont/fortnite-api#113]
Hi, 

I´m getting an error while trying to receive data from the leaderboards request with this messaage: "Sorry an error occurred and we were unable to resolve it (tracking id: [60b4d7d7-978d-47d9-8242-df40992c7e1e])" and error code 1000.

Do you have any ideas to solve this?

Thank you very much.

**Comment by qlaffont** [comment]
Yes. I try to fix but i don't know why it's not work. If you can try to found it it will be good ;)

**Comment by weeco** [comment]
It's because the request you are sending is invalid / not complete. Compare it with your fiddler results.

**Comment by qlaffont** [comment]
If you want to investigate you are free to make a PR ^^

**Comment by RobertoGraham** [comment]
[These changes](https://github.com/henhouse/fortnite-go/commit/548cf62a98d1a25bbf17b6e4a172b643d9a68947) will make it work! Thanks @henhouse for finding this

**Comment by qlaffont** [comment]
@RobertoGraham, You can make a PR to implement this ;)

**Comment by RobertoGraham** [comment]
#120
