### ISSUE TITLE
PVE Stats

### ISSUE THREAD

**Issue by Manerr** [qlaffont/fortnite-api#119]
Hi,
I noticed that getStatsPVE(username) is deprecated but I don't see any replacement function. However, some sites allow you to obtain stats about an user in PVE like stormshield.one, is that the fortnite api allows it. 
Can we hope this api will be updated?

**Comment by qlaffont** [comment]
Actually Epic have shutdown the previous version of PVE Request. But anyway, if you found a way to get it from another API or you know the way, you are free to make a PR ;).

**Comment by matiosfree** [comment]
Hey guys. Is here any update?
