### ISSUE TITLE
Fortnite Client Token

### ISSUE THREAD

**Issue by Awper-Dev** [qlaffont/fortnite-api#123]
Hey there! 
I found my Client launcher token using Fiddler 4 but I can't seem to find my Fortnite Client Token.
I'm looking for the correct request but I can only see the /account/api/oauth/exchange HTTP/1.1 request.
Could you help me with this?

**Comment by Tresmos** [comment]
#74

**Comment by qlaffont** [comment]
You can use this token : 
export TOKEN_LAUNCHER="MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=";
export TOKEN_CLIENT="ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=";
