### ISSUE TITLE
[ Security ] Is it secure enough? 

### ISSUE THREAD

**Issue by LukyVj** [qlaffont/fortnite-api#124]
Hello and thank you for making this. 

I'm really tempted to use this lib for an experiment of mine. I have one question tho. As you may know, today the Fortnite credentials are *data a lot of malicious people would love to get*. 

Therefore I'm wondering how secure it is to enter our own credentials before using this API. 

From what I've seen, they shounldn't leak anywhere, but just want to be sure. I've seen other APIs returning data without the use of any credentials, so I would love to know more. 

Thanks.

**Comment by qlaffont** [comment]
Hi Lucas,
Actually as you can see on source files, I didn't store any credentials.
You need to provide your credentials, and it's only used/see by you. Secure
& Independant is the best way ! 👌
Quentin
