### ISSUE TITLE
Problème stats joueur xbox

### ISSUE THREAD

**Issue by Valoroeckoi** [qlaffont/fortnite-api#127]
Bonjour, nous avons actuellement un problème pour récupérer les stats d'un joueur sur  (Xbox)
Son pseudo : RPPalestine15
Le lookup fonctionne, il trouve bien le pseudo et l'identifiant. : { id: '8b21781f1afa41459145262061f0c7b3',
  displayName: 'RPPalestine15' }
Mais pour les stats nous avons une erreur.
Stats undefined
Impossible to fetch User. User not found on this platform

Pourtant lorsqu'on recherche RPPalestine15 sur fortnitetracker ça trouve bien le compte avec ces stats.

https://fortnitetracker.com/profile/xbox/RPPalestine15

Auriez-vous des informations sur le problème ? 

Cordialement,

**Comment by monkeydioude** [comment]
On a eu ça avec un autre joueur, le joueur avait son compte en privé, le rendant impossible à trouver via les endpoints fournis par cette API, par contre fortnitetracker arrivait bien a mettre a jour ses informations.

Aucune idée de comment ils font. Possiblement un autre endpoint, ou complètement une autre façon de récupération des stats

**Comment by Valoroeckoi** [comment]
Merci pour la réponse, effectivement le problème venait de la 👍

**Comment by monkeydioude** [comment]
np :)

Peux tu fermer l'issue ?
