### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by jvdaa** [qlaffont/fortnite-api#130]
Fortnite-API - Credentials Params OK
Logged in as FortniteGamer#4714!
{ message: 'Please enter good token',
  err:
   { StatusCodeError: 400 - {"errorCode":"errors.com.epicgames.common.oauth.invalid_client","errorMessage":"It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.","messageVars":[],"numericErrorCode":1011,"originatingService":"com.epicgames.account.public","intent":"prod","error_description":"It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.","error":"invalid_client"}
       at new StatusCodeError (/mnt/c/Users/Jesper/github/FortniteGamer/node_modules/request-promise-core/lib/errors.js:32:15)
       at Request.plumbing.callback (/mnt/c/Users/Jesper/github/FortniteGamer/node_modules/request-promise-core/lib/plumbing.js:104:33)
       at Request.RP$callback [as _callback] (/mnt/c/Users/Jesper/github/FortniteGamer/node_modules/request-promise-core/lib/plumbing.js:46:31)
       at Request.self.callback (/mnt/c/Users/Jesper/github/FortniteGamer/node_modules/request/request.js:185:22)
       at Request.emit (events.js:182:13)
       at Request.<anonymous> (/mnt/c/Users/Jesper/github/FortniteGamer/node_modules/request/request.js:1161:10)
       at Request.emit (events.js:182:13)
       at IncomingMessage.<anonymous> (/mnt/c/Users/Jesper/github/FortniteGamer/node_modules/request/request.js:1083:12)
       at Object.onceWrapper (events.js:273:13)
       at IncomingMessage.emit (events.js:187:15)
       at endReadableNT (_stream_readable.js:1092:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     name: 'StatusCodeError',
     statusCode: 400,
     message:
      '400 - {"errorCode":"errors.com.epicgames.common.oauth.invalid_client","errorMessage":"It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.","messageVars":[],"numericErrorCode":1011,"originatingService":"com.epicgames.account.public","intent":"prod","error_description":"It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.","error":"invalid_client"}',
     error:
      { errorCode: 'errors.com.epicgames.common.oauth.invalid_client',
        errorMessage:
         'It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.',
        messageVars: [],
        numericErrorCode: 1011,
        originatingService: 'com.epicgames.account.public',
        intent: 'prod',
        error_description:
         'It appears that your Authorization header may be invalid or not present, please verify that you are sending the correct headers.',
        error: 'invalid_client' },
     options:
      { url:
         'https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token',

**Comment by Laphatize** [comment]
You're receiving this error because you most likely aren't sending the correct headers.

**Comment by qlaffont** [comment]
@jvdaa can you provide you code to check if everything is good please ?

**Comment by jvdaa** [comment]
```js
const Discord = require('discord.js');
const client = new Discord.Client();
const config = require('./config.json');
const Fortnite = require('fortnite-api')
const ms = require('ms');

client.on('ready', () => {
  console.log(`Logged in as ${client.user.tag}!`);
});

let fortniteAPI = new Fortnite([
  config.email, config.password, config.cltoken, config.fctoken
], {
  debug: true
});

client.on('message', message => {
  const prefix = config.prefix
  const args = message.content.slice(prefix.length).trim().split(/ +/g);
  const command = args.shift().toLowerCase();

  if (!message.content.startsWith(prefix) || message.author.bot)
    return;
  if (command === 'ftn' || command === 'fortnite') {
    message.delete().catch;

    comingSoon = new Discord.RichEmbed().setTitle("Coming Soon").setDescription("This feature is not available yet. Or currently disabled because of known bugs.").setColor("#7c0000");

    if (args[0] === 'link') {
      // Link
      message.channel.send(comingSoon)
    } else if (args[0] === 'unlink') {
      // Unlink
      message.channel.send(comingSoon)
    } else if (args[0] === 'status') {
      // Show BR Status
      message.channel.send(comingSoon)
    } else if (args[0] === 'compare') {
      // Compare player stats
      message.channel.send(comingSoon)
    } else if (args[0] === "rank") {
      // Give Fortnite Score
    } else if (args[0] === 'ps4') {
      // PS4 Stats
    } else if (args[0] === 'xbox') {
      // XB1 Stats
    } else {
      fortniteAPI.login().then(() => {
        let uid = args[0];
        let platform = args[1];
        if (!args[1]) {
          let platform = 'pc'
        }
        fortniteAPI
          .checkPlayer("Mirardes", "pc")
          .then(stats => {
            console.log(stats);
          })
          .catch(err => {
            console.log(err);
          });
      }).catch(err => {
        console.log(err);
      });
      // Get PC or Linked Stats
    }
  }

  if (command === 'botinfo') {
    // Botinfo
    message.delete().catch;
    let bicon = client.user.displayAvatarURL
    let embed = new Discord.RichEmbed().setTitle("Information").setDescription(`Information about ${client.user}`).setColor("#ffffff").setThumbnail(bicon).addField('Name', client.user.username, true).addField("Servers", client.guilds.size, true).addField("Uptime", ms(client.uptime), true).addField("Ping", `${client.ping}ms`, true);

    message.channel.send(embed);
  }






  if (command === 'github' || command === 'git') {
    // Github link
    message.delete().catch;
    let embed = new Discord.RichEmbed().setTitle("Information").setDescription("Link to Github Repository: https://github.com/jvdaa/FortniteGamer").setColor("#ffffff");
    message.channel.send(embed);
  }

  if (command === 'invite') {
    // Invite Link
    message.delete().catch;
    let embed = new Discord.RichEmbed().setTitle("Information").setDescription("Link to Bot Invitation: https://discordapp.com/oauth2/authorize?client_id=475929540858740736&scope=bot&permissions=8").setColor("#ffffff");
    message.channel.send(embed);
  }

  if (command === "support") {
    // Discord Support Server Link
    message.delete().catch;
    let embed = new Discord.RichEmbed().setTitle("Information").setDescription("Link to Support Server: https://discord.gg/B3V3xRj").setColor("#ffffff");
    message.channel.send(embed);
  }

  if (command === 'donate') {
    // Give Paypal Donate Link
    message.delete().catch;
    let embed = new Discord.RichEmbed().setTitle("Information").setDescription("Link to Paypal Donation: `currently not available`").setColor("#ffffff");
    message.channel.send(embed);
  }
});

client.login(config.token);
```

**Comment by qlaffont** [comment]
For me you have probably a problem with your token or with your account. 

Can you try with this token : 
config.cltoken => MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=

config.fctoken => ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=
