### ISSUE TITLE
Capturing Tokens

### ISSUE THREAD

**Issue by koflin** [qlaffont/fortnite-api#133]
Is it not possible to catch tokens anymore? It seems like epicgames is using a VPN.

**Comment by weeco** [comment]
They are using SSL pinning, but you don't need to capture tokens as they are static and not user related at all. This has been reported months ago, but qlaffont wasn't convinced that this is true I think. I hardcoded them in my own library where you just need to provide username/pass.

**Comment by qlaffont** [comment]
You can use this tokens : 
Can you try to reverse your two token ? "Mzh" before "ZW"

const Fortnite = require("fortnite-api");
exports.run = async (client, pool, serverSettings, message, args) => {
let config = client.config.fortnite_infos
let fortniteAPI = new Fortnite(
[
config.email,
config.pass,
"MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=",
"ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="
],
{
debug: true
}
);
await fortniteAPI.login()
fortniteAPI.getFortnitePVEInfo("fr")
.then(pveInfo => {
console.log(pveInfo);
})
.catch(err => {
console.log(err);
});
}
