### ISSUE TITLE
Problem username undefined

### ISSUE THREAD

**Issue by Valoroeckoi** [qlaffont/fortnite-api#134]
Bonjour, nous avons un problème avec le compte xbox de l'un de nos utilisateurs, son compte est bien en public. Il a un compte Epic-games et Xbox lié. Il est censé avoir comme account id celui-ci pour ces deux comptes : 
01fc7e62fa934be292bc5fcef2ff16ba

Pourtant lorsqu'on le recherche par son username (COGG3RLAN), impossible de voir ces stats, mais lorsque qu'on recherche par son accountid nous avons bien ces stats mais avec un pseudo "undefined" image ci-dessous.

https://gyazo.com/c9dd5b8801688f63e0ad79a452990f56

Et la chose bizarre étant qu'après être allé sur un site tiers qui permet d'obtenir les accounts id en fonction de l'username, celui-ci nous ressort un account id différent avec aucune stats sur  xb1 (username introuvable) : 4c11ddbf25124429b6b4253011dede1d

Quant à fortnitetracker, lorsqu'on recherche "COGG3RLAN", on tombe bien sur un compte xb1 et pc, et en inspectant le code source de sa page, on peut bien voir que l'id qui ressort et le suivant : 01fc7e62fa934be292bc5fcef2ff16ba

C'est comme-ci pour le même pseudo il y avait deux accounts id différents ce qui ferais interférence lorsqu'on essaye d'obtenir les stats avec l'username., auriez-vous des idées sur le problème ?

Cordialement,

**Comment by ImranDoet** [comment]
english please

**Comment by monkeydioude** [comment]
"COGG3RLAN" est son displayName, et "LUXURYBOYLDN" est son nickname. J'imagine qu'il y a une confusion à ce niveau là dans les resultats. 

J'avais déjà des doutes la dessus, mais je pense que Fortnitetracker à accès a des API qu'on a pas. Celles fournies par ce projet ne permettent que de request les nickname, pas les displayName.
En plus de ça, dans le code source, on voit que Fortnitetracker affiche le UUID de la personne en mode raw, pas concatenée comme requis par nos endpoints... Louche

----
"COGG3RLAN" is its displayName and "LUXURYBOYLDN" is its nickname. I believe there is a confusion aroud this.

I already had doubts about this, I am pretty sure that Fortnitetracker has access to APIs that we don't. Those provided thru this repo only allow request to nickname, not displayName.
Furthermore, inside the source code of Fortnitetracker, we can clearly see the UUID of the user displayed raw style, not concatened as the endpoints we use require... Odd

**Comment by Valoroeckoi** [comment]
Merci de ta réponse, oui effectivement j'ai parlé avec la personne hier et il a modifié son pseudo en "LUXURYBOYLDN" et maintenant tout marche parfaitement, d'après lui le problème était : it was just that my Xbox was linked to an account with no email so I had to create a new user and email in the epic account and then reconnect.
