### ISSUE TITLE
Unhandled promise rejection error

### ISSUE THREAD

**Issue by MadLeaker** [qlaffont/fortnite-api#135]
I am getting this problem when i run my program, i used the fortnite api correctly but idk why it does that error
![image](https://user-images.githubusercontent.com/43907203/46571120-f72cce00-c977-11e8-8e86-e014369af572.png)

**Comment by MadLeaker** [comment]
its happening on the login method of the api

**Comment by qlaffont** [comment]
Can you give your code please ?

**Comment by eeeAAAkkk** [comment]
@qlaffont I'm having the same issue. Unfortunately I tried to pull too many stats from the server and generated too many sessions. Happened already sometimes, I changed the password and was able to login again, not this time.

So I was having the same error message as on the screen above and so I checked the coding of the login function. I added a catch block for the "return new promise" to get more details.

that's my result. Complete log is around 4 "pages" in terminal.

message: 'Please enter good token',
  err: 
   { StatusCodeError: 429 - {"errorCode":"errors.com.epicgames.common.throttled","errorMessage":"Operation access is limited by throttling policy, please try again in 6798 second(s).","messageVars":["6798"],"numericErrorCode":1041,"originatingService":"com.epicgames.account.public","intent":"prod"}
