### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Brendan4528** [qlaffont/fortnite-api#136]
wot? how do i get up and coming item shops?

**Comment by monkeydioude** [comment]
This is not a forum asking for assistance, this is an issue tracker. Try finding yourself the answer, the project is well documented.
Now if you find a problem with the code itself, you can open an issue **with a proper name**.

Thank you.

**Comment by Brendan4528** [comment]
can i even get tommarows item shops?
and is there a video that can help me install this?
