### ISSUE TITLE
Getting 0 from Stats

### ISSUE THREAD

**Issue by ikkyy** [qlaffont/fortnite-api#137]
Does someone has the same problem?

![capturar](https://user-images.githubusercontent.com/5765990/46672402-b1594b00-cbad-11e8-8409-c9fa51862348.JPG)

**Comment by qlaffont** [comment]
I don't see any problem.

**Comment by ikkyy** [comment]
I am not getting stats from some points.
Like Solo, Top3, Top 5
Duo, Top3, 10, 25
Squad Top5,10,25

**Comment by qlaffont** [comment]
As I can see, your top 3 total is similar to Squad top 3. Same for the others, so is not a problem. It's just the exact stat of Epic Games give us.

**Comment by monkeydioude** [comment]
Solo Top3 and Top5 doesnt exist.

Top3 is Squad only, top5 is Duo only. As well as top10 and top25 is for solo only

**Comment by weeco** [comment]
Maybe there are no wins for top3 of solo/duo for instance @monkeydioude ?

**Comment by monkeydioude** [comment]
No, it's a general design rule from EPIC. top3 and top5 in solo does not exist, the closest is top10.
Roughly, top10 solo = top3 squad =  top5 duo
I think they designed this to be equivalent, as followed:
- top10  solo contains 10 players.
- top3 squad, as it's for teams, might contains ~10 players (besides extreme exception).
- top5 duo contains ~10 players.

**Comment by Jericho1060** [comment]
like Monkey said, there are only two types of stats for each kind of game :
 - Solo = top 10 / 25
 - duos = top 5 / 12
 - squads = top 3 / 6

Epic is just giving an average amount that said you are one of the (around) 25 last players (top 25 solo, 12 duos: 12*2=24, 6 squads: 6*4=24) or one of the (around) 10 last players (top 10 solo, top 5 duos : 5*2=10, top 3 squad: 3*4=12)
