### ISSUE TITLE
No 'Access-Control-Allow-Origin' 

### ISSUE THREAD

**Issue by ghost** [qlaffont/fortnite-api#141]
Hi, in my console when i launch my first page i have this error. I think my code not working with your package but i have this line before error 'Fortnite-API - Credentials Params OK'. I'm lost. I have checked couple times my token.
This is the full console log:
- Fortnite-API - Credentials Params OK

- Failed to load https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

- Uncaught (in promise) {message: "Please enter good token", err: RequestError}

thks for helping me

**Comment by monkeydioude** [comment]
CORS isn't related directly to the code, it's a server side problem https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.

**Comment by Smabi** [comment]
Thks for feedback, i have try to solved this error today. I continue tomorrow

**Comment by monkeydioude** [comment]
@qlaffont could help you more than me on this. Maybe it would be useful to allow injection of a CORS rule as a config to this API.

**Comment by weeco** [comment]
Probably you are using the library on the frontend? That doesn't work as all major browsers support CORS.

**Comment by Smabi** [comment]
yah i'm using it on the front-end in a rails app, i try to install gem rack-cors to fixed that.
