### ISSUE TITLE
Player not found error after 4 hours of inactivity

### ISSUE THREAD

**Issue by JDaatselaar** [qlaffont/fortnite-api#142]
Hello, I'm using this Fortnite-API a very long time. Until my Discord bot was finally finished, I never got an error. 

So today I tested my bot, with your API, for a couple hours. And then this happened.
```
Fortnite - API - Credentials Params OK
Logged in as FortniteGamer #4714!

JDaatselaar pc

biggetje6_fan pc

Biggetje6_fan pc

Biggetje6_fan pc

JDaatselaar pc
```

All that worked fine. But then I let it be inactive for 4 hours. And after that. Every user I checked i got the error `Player Not Found`. (Still the same run)

```
JDaatselaar pc

Player Not Found

JDaatselaar pc

Player Not Found

JDaatselaar pc

Player Not Found

Biggetje6_fan pc

Player Not Found

Biggetje6_fan pc

Player Not Found
```

So then i thought. Let's restart the discord bot. And Then it started working again, without an error:
```
Fortnite-API - Credentials Params OK

Logged in as FortniteGamer# 4714!
    
JDaatselaar pc

JDaatselaar pc
```

And I don't know how to fix it. 

[My Code](https://github.com/jvdaa/FortniteGamer "My Github Repository")

**Comment by Michele404** [comment]
You should refresh the access token because it got a time to expire. I have no idea how do it in javascript but its the way :)

**Comment by eeeAAAkkk** [comment]
@jvdaa I think to solve this you can put the .login after client.on('message', (message) => {

Then you will get a new session for every command. Think about killing the session otherwise you might get too many logins.

**Comment by qlaffont** [comment]
Logically I have created a routine to check token validity. (Function checkToken()). I will add a function named refreshToken().
