### ISSUE TITLE
Wrong response from API

### ISSUE THREAD

**Issue by Michele404** [qlaffont/fortnite-api#145]
With this API:
https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/stats/accountId/ + account + /bulk/window/ + time
I got this type of response and not the stats. Why?
[
	{
		"name": "br_score_pc_m0_p10",
		"value": 29621,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_score_pc_m0_p9",
		"value": 23711,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_matchesplayed_pc_m0_p10",
		"value": 162,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop3_pc_m0_p9",
		"value": 15,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_score_pc_m0_p2",
		"value": 7264,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_kills_pc_m0_p2",
		"value": 109,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_matchesplayed_pc_m0_p2",
		"value": 45,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_kills_pc_m0_p9",
		"value": 285,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_matchesplayed_pc_m0_p9",
		"value": 104,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop12_pc_m0_p10",
		"value": 43,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop1_pc_m0_p10",
		"value": 6,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop10_pc_m0_p2",
		"value": 8,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop25_pc_m0_p2",
		"value": 17,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop5_pc_m0_p10",
		"value": 23,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_kills_pc_m0_p10",
		"value": 421,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop6_pc_m0_p9",
		"value": 28,
		"window": "weekly",
		"ownerType": 1
	},
	{
		"name": "br_placetop1_pc_m0_p9",
		"value": 9,
		"window": "weekly",
		"ownerType": 1
	}
]

**Comment by RobertoGraham** [comment]
https://github.com/qlaffont/fortnite-api/blob/master/tools/stats.js#L39 If you look at the `convert` function exported by this file, you'll see how this library's stats object is built from that response

**Comment by Michele404** [comment]
is there a method to get it automatically?
