### ISSUE TITLE
Unable to parse command com.epicgames.fortnite.core.game.commands.QueryProfile. Could not deserialize payload for com.epicgames.fortnite.core.game.commands.QueryProfile

### ISSUE THREAD

**Issue by Thesevs** [qlaffont/fortnite-api#148]
So, im trying to retreive the AthenaCharacter ids using: https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/accountid/client/QueryProfile?profileId=athena&rvn=-1 but this gave me the error you can see in the title. Does anyone know why this happens?

**Comment by qlaffont** [comment]
Use the api, not direct link :).

**Comment by Thesevs** [comment]
What do you mean?

**Comment by Maiu15** [comment]
I didn't use the direct link. I tried retrieving the info using curl, but it gave me that error. @qlaffont

**Comment by qlaffont** [comment]
You can check on the code how I do that. I will not provide support except
for person that use this library.

Cordialement

Quentin LAFFONT
8 lot parc du chateau
13190 ALLAUCH
06.29.86.98.41
http://qlaffont.com

**Comment by Maiu15** [comment]
I can’t find any file where you retrieve skins/items? @qlaffont
