### ISSUE TITLE
Why are ingame post requests not supported?

### ISSUE THREAD

**Issue by encloinc** [qlaffont/fortnite-api#149]
By this I mean there are no functions in the api to manage ones account inside fortnite (game purchases, friend requests and even the new gifting system would be great additions)

**Comment by Jericho1060** [comment]
Hi, several reason can explain that.
I think the main one is the security.
Even if it's technically possible, including such a feature would also need to add a lot of security around the project and that's a lot of work to do and to maintain.
This api if mainly made to access stats from Fortnite, not from Epic Games account.

**Comment by encloinc** [comment]
Well

> Hi, several reason can explain that.
> I think the main one is the security.
> Even if it's technically possible, including such a feature would also need to add a lot of security around the project and that's a lot of work to do and to maintain.
> This api if mainly made to access stats from Fortnite, not from Epic Games account.

Well if anyone wants to do that sort of thing, I made this utility https://github.com/encloinc/Nitelite

**Comment by Jericho1060** [comment]
I had a fast look at your project and it's exactly what i was saying.
No security is done on it.
Username and password are not encrypted on client side (your project). Personnaly, I don't want my player account informations to be stored on my PC like that. 
Other point: no support for the second authentication factor.
The api here is made for stats, and can be used with any account for any user. This is permiting to use a dedicated account. Not a real player account.

**Comment by Jericho1060** [comment]
Be carefull with the anti-cheat protection from Epic Games with that tool :D

**Comment by encloinc** [comment]
It only controls the launcher as of now

**Comment by Jericho1060** [comment]
i know, but this is near how works an aim bot, the Epic Games detector could identify it as a cheat and ban users
