### ISSUE TITLE
fix token 0_o

### ISSUE THREAD

**Issue by bozoweed** [qlaffont/fortnite-api#153]
hello i get this ....
"Login is banned or does not posses the action 'PLAY' needed to perform the requested operation for platform

**Comment by bozoweed** [comment]
it's okey use this it's the new token launcher 
"MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=",

**Comment by bozoweed** [comment]
`"tokenClientFortniteTracker": "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=",
	"tokenLauncherFortniteTracker": "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=",
`

**Comment by qlaffont** [comment]
Thanks I have updated the token on Readme :)
