### ISSUE TITLE
Your github link is redirecting to another fortnite api, not your.

### ISSUE THREAD

**Issue by Manaf941** [qlaffont/fortnite-api#162]
The github link on npm for your package is not redirecting to the right github. It redirect to https://github.com/Jake-Ruston/fortnite#readme.
![first screen](https://user-images.githubusercontent.com/42099539/50785426-e3637180-12b0-11e9-9bcd-80cb3a2db011.png)
![capture d ecran 254](https://user-images.githubusercontent.com/42099539/50785439-f24a2400-12b0-11e9-9730-2c9928b9a441.png)

**Comment by Manaf941** [comment]
je viens de voir que tu viens de la france donc en français: Le lien github sur npm envoie vers une autre api fortnite, pas la tienne

**Comment by qlaffont** [comment]
Okay I will fix it

**Comment by qlaffont** [comment]
Thanks to your help ! It's now fix on NPM ;).
