### ISSUE TITLE
No content on stats request

### ISSUE THREAD

**Issue by RayzonDE** [qlaffont/fortnite-api#165]
Hey guys,
I don't know what's wrong if I try to request the stats of new users, I get http code 204 (no content). It works if I request a ID which I already requested in the last months but I can't request new IDs.
The http curl info: 
`{"url":"https:\/\/fortnite-public-service-prod11.ol.epicgames.com\/fortnite\/api\/stats\/accountId\/90a7014a1e2d4ee6b316f01178a62f44\/bulk\/window\/alltime","content_type":null,"http_code":204,"header_size":254,"request_size":2118,"filetime":-1,"ssl_verify_result":0,"redirect_count":0,"total_time":0.361379,"namelookup_time":3.0e-5,"connect_time":0.087731,"pretransfer_time":0.267024,"size_upload":0,"size_download":0,"speed_download":0,"speed_upload":0,"download_content_length":0,"upload_content_length":-1,"starttransfer_time":0.361348,"redirect_time":0,"redirect_url":"","primary_ip":"54.209.17.125","certinfo":[],"primary_port":443}`

I can request account information or the psn id or somethink like that of this IDs but not the stats I don't understand what's wrong. I'm using user-agent "Fortnite/++Fortnite+Release-7.01-CL-4644078 IOS/11.3.1" can someone help me?

**Comment by qlaffont** [comment]
You don't use the api here no ?

**Comment by RayzonDE** [comment]
@qlaffont 
no I use my own private system but we are using the same endpoints so I hoped someone here can help me

**Comment by qlaffont** [comment]
I will not provide any support so.
