### ISSUE TITLE
Can't request user stats

### ISSUE THREAD

**Issue by RayzonDE** [qlaffont/fortnite-api#166]
I'm here again but this time I got a error in the fortnite-api script ^^
so I don't know what's wrong if I try to request the stats of new users, I get `{ message: 'Impossible to fetch User. User not found on this platform' }`. It works if I request a Users which I already requested in the last months but I can't request the stats of new Users only their account data.

Thats my code:

> fortniteAPI.login().then(() => {
>     fortniteAPI
>         .getStatsBR("paxp", "pc", "weekly")
>         .then(stats => {
>             console.log(stats);
>         })
>         .catch(err => {
>             console.log(err);
>         });
> });

Do you guys get an error, too if you request the player paxp?
And do anyone know where the problem is?

**Comment by qlaffont** [comment]
I don't know. Epic Games don't return any stats about this player. I don't know why. So I can't do anything.

**Comment by RayzonDE** [comment]
It's the privacy settings btw, for the users which has the same problem.
