### ISSUE TITLE
Token have changent

### ISSUE THREAD

**Issue by Kiko017** [qlaffont/fortnite-api#168]
I didn't yet find Fortnite one. But here is the Launcher's one:
MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=

**Comment by qlaffont** [comment]
Actually, the other token is working. If it will not working, I will change it to Readme.

**Comment by Kiko017** [comment]
Not working. I always get with the old tokens "forbidden error"

**Comment by qlaffont** [comment]
What is your token you used actually ?

>

**Comment by qlaffont** [comment]
As you can see, everything is working when I run tests. Can you provide the
piece of code you execute please ?

>

**Comment by qlaffont** [comment]
https://ibb.co/BKjB84w

**Comment by Kiko017** [comment]
const Fortnite = require("fortnite-api");

let fortniteAPI = new Fortnite(
    [      
        "christophermadi.mls@gmail.com",
        "Christopher12345",
        "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=",
        "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="
    ],
    {
        debug: true
    }
);

fortniteAPI.login().then(() => {
    fortniteAPI.getStore("fr")
    .then(store => {
        console.log(store)
    }).catch(err => {
        console.log(err)
    })
});


Si tu veux test toi même

**Comment by Kiko017** [comment]
Pour plus de détails: j'ai creer un Visual Studio file dans le Folder fortnite-api-master. Et dans visual studio j'ai écrit ce code et l'ai exécuter

**Comment by qlaffont** [comment]
First, your code is not updated with the last version of Fortnite API.
I have tried with your credentials, but you are blocked by Epic Games API.
(Your account is ban? Have you tried to connect you in Game to check if you
have any problem?
Your new token doesn't work at this time. I have tried with my account.

>

**Comment by Kiko017** [comment]
I created the account today as a test(I don't want to use my main account).
I verified the email/log in in Epic Games Launcher. All is fine.

**Comment by Kiko017** [comment]
Can you send me the correct code pls? And for the new token , when I tested with Fiddlee I got the one I put above

**Comment by DanyIonut2580** [comment]
heyy i need api token
