### ISSUE TITLE
Not working(Event Flag/shop/etc...)

### ISSUE THREAD

**Issue by Kiko017** [qlaffont/fortnite-api#169]
Here is my code
const Fortnite = require("fortnite-api");

let fortniteAPI = new Fortnite(
    [
        "ryanfares9@gmail.com",
        "Ryan2018",
        "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=",
        "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="
    ],
    {
        debug: true
    }
);

fortniteAPI.login().then(() => {
    fortniteAPI
        .eventFlags()
        .then(data => {
            console.log(data);
        })
        .catch(err => {
            console.log(err);
        });
});

**Comment by Kiko017** [comment]
I am only getting this:]
![unknown](https://user-images.githubusercontent.com/33565739/51440970-48698f00-1cd5-11e9-84da-38b832b9b360.png)

**Comment by Kiko017** [comment]
![unknown](https://user-images.githubusercontent.com/33565739/51440979-6c2cd500-1cd5-11e9-91f8-30eb1593a7a3.png)

**Comment by Kiko017** [comment]
Even the shop
![unknown](https://user-images.githubusercontent.com/33565739/51440988-8666b300-1cd5-11e9-80a0-7b006050ea7a.png)

**Comment by Kiko017** [comment]
const Fortnite = require("fortnite-api");

let fortniteAPI = new Fortnite(
    [
        "ryanfares9@gmail.com",
        "Ryan2018",
        "MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=",
        "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="
    ],
    {
        debug: true
    }
);

fortniteAPI.login().then(() => {
    fortniteAPI
        .getStore("fr")
        .then(store => {
            console.log(store);
        })
        .catch(err => {
            console.log(err);
        });
});

**Comment by qlaffont** [comment]
The data are working is just your node don't display all data :
You can do this with this :
```
const FortniteAPI = require("../.");
const util = require('util');

util.inspect.defaultOptions.maxArrayLength = null;

//Set Max Timeout Mocha
let fAPI = new FortniteAPI([
    process.env.EMAIL,
    process.env.PWDACCOUNT,
    process.env.TOKEN_LAUNCHER,
    process.env.TOKEN_CLIENT
]);

fAPI.login().then(() => {
    fAPI
        .eventFlags()
        .then(data => {
            console.log(util.inspect(data, {
                showHidden: false,
                depth: null
            }));
        })
        .catch(err => {
            console.log(err);
        });
})
.catch((err) => {
    console.log("Credentials not good", err);
});
```

**Comment by Kiko017** [comment]
So it become:

const FortniteAPI = require("../.");
const util = require('util');

util.inspect.defaultOptions.maxArrayLength = null;

//Set Max Timeout Mocha
let fAPI = new FortniteAPI([
    process.env.email@email.com,
    process.env.lolIamlol,
    process.env.MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=,
    process.env.TOKEN_CLIENT
]);

fAPI.login().then(() => {
    fAPI
        .eventFlags()
        .then(data => {
            console.log(util.inspect(data, {
                showHidden: false,
                depth: null
            }));
        })
        .catch(err => {
            console.log(err);
        });
})
.catch((err) => {
    console.log("Credentials not good", err);
});

**Comment by qlaffont** [comment]
You don't understand javascript so I will not help you.

**Comment by Kiko017** [comment]
Exactly and don't understand JavaScript. U can just tell me all the code I
need and I can copy paste it. Pls

**Comment by benjaminrobinet** [comment]
> You don't understand javascript so I will not help you.

men are trash
