### ISSUE TITLE
Stats V2 Endpoint

### ISSUE THREAD

**Issue by RobertoGraham** [qlaffont/fortnite-api#170]
New stats endpoint: `https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/statsv2/account/:accountId`

There's new stat type, "playersoutlived". Time windows are now done with `startTime` and `endTime` query  parameters. Concept of platforms is gone and stats are now filtered by input types, i.e. `keyboardmouse`, `gamepad`, and `touch`. Also LTM stats are included in response.

**Comment by fabriciols** [comment]
Hi @RobertoGraham how did you find this info? I tried to look at fortnite logs but it do not show this endpoint

**Comment by RobertoGraham** [comment]
@fabriciols It was discovered by [Kysune](https://github.com/SzymonLisowiec) in the Fortnite app dev discord. I'm unsure of his exact methods

**Comment by SL-x-TnT** [comment]
@fabriciols If you have an Android device that can run Fortnite, I found it through that.
Add frida gadget to the apk. I used objection to automate that. My device isn't rooted, so I had to go with this. `https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/`
Hooked the ssl3_write and ssl3_read in the libUE4.so module using `Interceptor.attach`.

**Comment by ConnorLinfoot** [comment]
@RobertoGraham Have you managed to get `startTime` and `endTime` to work? I've attempted to provide it with a unix timestamp as well as a few other variations and it seems to just return the all-time stats with the only difference being that the response includes the start and end times that I provided.

**Comment by RobertoGraham** [comment]
@ConnorLinfoot Yes it's bugged right now, supposedly there's a fix coming in the following days
![image](https://user-images.githubusercontent.com/14958777/53063388-d34bce00-34bb-11e9-88b2-0a13facc2bc5.png)

**Comment by InkedCurtis** [comment]
Does anyone have any idea whether or not we can grab recent match results/history on a match per match basis? I'm struggling to find this out...

**Comment by qlaffont** [comment]
You can make a PR if you want to improve the api :)

**Comment by Beat-YT** [comment]
> @fabriciols If you have an Android device that can run Fortnite, I found it through that.
> Add frida gadget to the apk. I used objection to automate that. My device isn't rooted, so I had to go with this. `https://blog.netspi.com/four-ways-bypass-android-ssl-verification-certificate-pinning/`
> Hooked the ssl3_write and ssl3_read in the libUE4.so module using `Interceptor.attach`.

@SL-x-TnT  Can you add me on Discord? Beat YT#2021
