### ISSUE TITLE
Some users in PSN not returning in the api

### ISSUE THREAD

**Issue by akairu** [qlaffont/fortnite-api#172]
The following player has a  PSN Account and the api is returning "Impossible to fetch User. User not found on this platform"
but if you look for the player in https://fortnitetracker.com/profile/psn/estano2002
you are able to see his stats

**Comment by mlcsthor** [comment]
I have the same problem with the username of a PC-only player. The API returns "Impossible to fetch User. User not found on this platform" but I can find it on Fortnite Tracker (https://fortnitetracker.com/profile/pc/Zelenion)

**Comment by qlaffont** [comment]
Here, A PSN account can work only if his account is link to Epic Games Account
