### ISSUE TITLE
cups stats api?

### ISSUE THREAD

**Issue by vseveryn** [qlaffont/fortnite-api#174]
are there any (leaderboards etc)? tried to sniff in-game cup leaderboard, but didn't see any http requests, seems like client loads it via tcp...

**Comment by qlaffont** [comment]
If it's load by tcp we need to inspect how to do that.

**Comment by Amrsatrio** [comment]
Leaderboards API:
events-public-service-live.ol.epicgames.com/api/v1/leaderboards/Fortnite/{eventId}/{eventWindowId}/{accountId}?page={page}&rank=0&teamAccountIds=&appId=Fortnite&showLiveSessions=true

**Comment by qlaffont** [comment]
Please create a PR for this :)
