### ISSUE TITLE
UnhandledPromiseRejectionWarning: #<Object>

### ISSUE THREAD

**Issue by markito12** [qlaffont/fortnite-api#181]
i dont know why it happends, i disabled 2fa and still.

```
let fortniteAPI = new Fortnite(
    [
        "mymail@gmail.com",
        "pass",
        "MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y=",
        "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="
    ]
);

fortniteAPI.login().then(() => {

});
```
and the email and pass are from epic games launcher?

**Comment by Lk2v** [comment]
I have the same problem these tokens are no longer valid, otherwise yes it is necessary to put the identifier of the launcher

**Comment by markito12** [comment]
yes, so frustrating

**Comment by vanerac** [comment]
try `fortniteAPI.login().catch(e => {console.log(e)})`
