### ISSUE TITLE
Can't get launcher tokens

### ISSUE THREAD

**Issue by Lk2v** [qlaffont/fortnite-api#182]
Despite my several attempts I can't get the `client launcher token` I can't find any address in _Fiddler_ corresponding to `/account/api/oauth/token` the only other mentions I found when doing a search are this one but I don't think they are the right ones  
Does anyone have a technique to access the tokens?

Thank you.

![image](https://user-images.githubusercontent.com/26687216/59551789-4e5f5580-8f7f-11e9-90b0-aacb06fcaa54.png)
![image](https://user-images.githubusercontent.com/26687216/59551826-9f6f4980-8f7f-11e9-9698-42c9d43f6b03.png)

**Comment by Vanerac** [comment]
Use the ones in Readme

**Comment by Lk2v** [comment]
I tried, but it doesn't work...

**Comment by Vanerac** [comment]
Can you show your code?

**Comment by Lk2v** [comment]
here is my code :
![Capture](https://user-images.githubusercontent.com/26687216/60624374-6808f580-9de5-11e9-98d9-b62c1d7ad7f5.PNG)

**Comment by Vanerac** [comment]
it works for me, do you have 2 factor authentification ?

**Comment by Lk2v** [comment]
Yes, I enabled it.
![image](https://user-images.githubusercontent.com/26687216/60649824-1b540780-9e43-11e9-9ce1-5e94ea083870.png)

**Comment by Vanerac** [comment]
I checked and it shouldn't be a problem,you could try and isable it to see if it fixes anything , when does it break, on startup? Or when I tries to get the refresh token?

**Comment by Lk2v** [comment]
It breaks at the time of the `fortniteAPI.login()` by putting a `catch()` I was able to get this information : 
```JavaScript
{ message:
   'Please enter good credentials (Login/Username/Launcher Token)',
  err:
   { Error: Request failed with status code 431
       at createError (D:\Projet\bot-fortnite-shop\node_modules\axios\lib\core\createError.js:16:15)
       at settle (D:\Projet\bot-fortnite-shop\node_modules\axios\lib\core\settle.js:17:12)
       at IncomingMessage.handleStreamEnd (D:\Projet\bot-fortnite-shop\node_modules\axios\lib\adapters\http.js:237:11)
       at IncomingMessage.emit (events.js:194:15)
       at endReadableNT (_stream_readable.js:1125:12)
       at process._tickCallback (internal/process/next_tick.js:63:19)
     config:
      { url:
         'https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/token',
        method: 'post',
        data:
         'grant_type=password&username=<username>&password=<password>&includePerms=true',
        headers: [Object],
        transformRequest: [Array],
        transformResponse: [Array],
        timeout: 0,
        adapter: [Function: httpAdapter],
        responseType: 'json',
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus] },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'POST /account/api/oauth/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nAuthorization: basic MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=\r\nUser-Agent: axios/0.19.0\r\nContent-Length: 94\r\nHost: account-public-service-prod03.ol.epicgames.com\r\nConnection: close\r\n\r\n',  
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/account/api/oauth/token',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     response:
      { status: 431,
        statusText: '',
        headers: [Object],
        config: [Object],
        request: [ClientRequest],
        data: [Object] },
     isAxiosError: true,
     toJSON: [Function] } }
```

**Comment by vanerac** [comment]
[`431 Request Header Fields Too Large`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431)

This can be caused because one of the fields in the header is too long

**Comment by vanerac** [comment]
what version are you using

**Comment by Lk2v** [comment]
This error is strange combined my password and email address are only 35 characters in length.

**Comment by qlaffont** [comment]
I know that sometimes, 2FA generate some problems in login. Can you try to disable it and try again ?

**Comment by qlaffont** [comment]
To check, I have run my tests, and everything is working. (https://github.com/qlaffont/fortnite-api/blob/master/test/index.js)

TOKEN_LAUNCHER="MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=";
TOKEN_CLIENT="ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=";

**Comment by MrPowerGamerBR** [comment]
Can confirm, you need to disable two factor authentication of your Epic Games account, if not, the API will throw `431 Request Header Fields Too Large`

**Comment by MrPowerGamerBR** [comment]
Also, a tip for anyone that tried creating a alt Epic Games account to use the API (just so you didn't need to disable 2FA on your main account): You need to login into Fortnite at least once, if you don't do that, the API will throw `403 Forbidden` (and some endpoints, like the player status, will return "Player not found" even if the player exists)

@qlaffont I think it would be nice if you added to the readme that:
* You need to disable two factor authentication before using the API, or else it will throw errors
* You need to login at least once to Fortnite to the API to work, if not it will throw `403 Forbidden` errors.

Just so other people doesn't get stuck on the same issues! 😊

**Comment by qlaffont** [comment]
Yes, no problem I will edit the readme ;).

**Comment by Lk2v** [comment]
Sorry for the long absence.
I just did what you were advised and it works
Thank you very much !

**Comment by DanyIonut2580** [comment]
I want the new fortnite api
