### ISSUE TITLE
Add supported languages to the readme

### ISSUE THREAD

**Issue by MrPowerGamerBR** [qlaffont/fortnite-api#185]
There was already a issue talking about this (kind of), but it was closed: https://github.com/qlaffont/fortnite-api/issues/68

It would be nice if in the readme there was all supported languages on the endpoints, some are easy to find out, but some (like brazilian portuguese) I couldn't figure out what it is.

**Comment by MrPowerGamerBR** [comment]
Worth nothing that the API (not Epic's, this API) restricts the language, so if you want to try finding other languages, you need to remove the language checks from the repo.

**Comment by MrPowerGamerBR** [comment]
Portuguese (Brazilian) language code: `pt-BR`

How I found it: I enabled Fiddler and clicked on the "Store" button on Epic Games' Launcher, there was a ` /store/pt-BR/api/content/promotions/epic-mega-sale` URL, so I tried using it and... it worked.

I also decompressed the pak files and *technically* these are all the supported languages for the store:
![https://cdn.discordapp.com/attachments/513404370931417088/605050322062409728/unknown.png](https://cdn.discordapp.com/attachments/513404370931417088/605050322062409728/unknown.png)

But I tried some of those language codes... and not every single one of them worked, so try them out, if it works, yay!

**Comment by qlaffont** [comment]
I have changed how the API use Language. You can see the change on the readme in the new release (v3.4.0).

You can provide an options object to ignore the language check.
