### ISSUE TITLE
[BUG] language bug

### ISSUE THREAD

**Issue by ljesparis** [qlaffont/fortnite-api#188]
**Version Used**
Which version you used ?
the last one

**Client Type**
Node.JS Application / JS Application (React, Angular) / Native JS Application.
nodejs app

**Describe the bug**
i think fortnite stoped using this header **X-EpicGames-Language** to translate their news or others

**To Reproduce**
Steps to reproduce the behavior.
well.. run the method **getFortniteNews**

**Additional context**
i test it from my firefox browser and Accept-Language header works, at least for me.

**Comment by qlaffont** [comment]
Yes, I think they change how to proceed to change language too. I will check.

**Comment by qlaffont** [comment]
Strange, it works on other Route who use the same header. Need help on this !

**Comment by ljesparis** [comment]
ok, let me help you this weekend that i'm free...

i will do some test ...  =)

**Comment by qlaffont** [comment]
I don't have time anymore to work on this repository. If you have any bug/new features, you can make a PR ! I will only fix security issues and merge PRs.
