### ISSUE TITLE
STW Returns invalid method with GET

### ISSUE THREAD

**Issue by JaydenMaalouf** [qlaffont/fortnite-api#20]
Awesome API dudes. Really helped me get my own off the ground!
Just wondering how to retrieve STW stats? Still a lil stuck on this one

**Comment by qlaffont** [comment]
Actually I don't know ! I need to take some time to search !

**Comment by JaydenMaalouf** [comment]
I also have a few things I can contribute to this API btw. Is there a way I can contact you privately? IE. Discord?

**Comment by qlaffont** [comment]
Yes for sure ! 👍 

To contact me privately, you have my discord Mirardes#2385 or my discord server dedicated for the API and my site stats-fortnite.com => https://discord.gg/PurBeRF
