### ISSUE TITLE
Tokens do not work.

### ISSUE THREAD

**Issue by bloehle13** [qlaffont/fortnite-api#26]
Following the instructions, I got Fiddler 4, and got my two tokens from the header via opening the launcher and opening the game. I removed the word "basic" from the front, too. Yet, each time I try to run the code, I get this: "Uncaught (in promise) Please enter good token"

I believe this to be an issue in your code, but if I'm wrong, please help me correct this issue.

Thank you!

**Comment by qlaffont** [comment]
Check again the ReadMe.md. Many user like me use this api and no body don't have any problem to use it. Follow each instructions, it's tricky i know but you need to do it !

**Comment by bloehle13** [comment]
I did some more research and I think Fortnite changed how you access their information. Can you try your code and see if it still works? If it does I'll try the README again.

**Comment by bloehle13** [comment]
No matter how many times I walk through the README, I get this error everytime:

`PlayerStats.js:20455 Uncaught (in promise) TypeError: Cannot read property '0' of null
    at Node.$.each (PlayerStats.js:20455)
    at initialize.exports.each (PlayerStats.js:17015)
    at Promise (PlayerStats.js:20452)
    at <anonymous>
$.each @ PlayerStats.js:20455
exports.each @ PlayerStats.js:17015
Promise @ PlayerStats.js:20452
async function (async)
Promise @ PlayerStats.js:20444
module.exports @ PlayerStats.js:20444
391.fortnite @ PlayerStats.js:41810
s @ PlayerStats.js:1
e @ PlayerStats.js:1
(anonymous) @ PlayerStats.js:1`

FYI, PlayerStats.js is simply a merged file that contains the `require(fortnite-api)`. This was done using Browserify to allow my work in the Cordova Framework

**Comment by qlaffont** [comment]
PlayerStats.js ? Are you sure you use my API ?

I have test my API right now and i have no error. I'm sure that your token is not good ! I have check with other developer who use my API and no error. So your error come from you.

**Comment by bloehle13** [comment]
The PlayerStats.js was my own class used for testing your API, that is not important. 

I agree the issue is with my tokens. However, I am having a really hard time getting the tokens correct. I see the two different ones in the headers of the oauth/token requests, but nothing seems to work. Would you mind helping me out please?

**Comment by qlaffont** [comment]
I don't have any time actually but you can ask to other dev in discord : https://discord.gg/PurBeRF
