### ISSUE TITLE
login

### ISSUE THREAD

**Issue by SkYNewZ** [qlaffont/fortnite-api#29]
Hi! Hi! After several tests of my API today, I have an error `Please enter a good token`. While searching on the EPIC GAMES side, it returns the error to me `errors.com.epicgames.account.oauth.too_many_sessions`. Would it be possible, in order to authenticate and use the EPIC GAMES API, to just provide the login and password to your module, which will take care of the necessary tokens for the continuation?
Because as a result, I am currently unable to connect to epic games, and my application is also unavoidable.

------

Hello! Après plusieurs tests de mon API aujourd'hui, j'ai une erreur `Please enter a good token`. En cherchant côté EPIC GAMES, il me retourne l'erreur`errors.com.epicgames.account.oauth.too_many_sessions`. Serait-il possible, pour s'authentifier et utiliser l'API EPIC GAMES, de fournir juste le login et password à ton module, qui s'occuperai des tokens nécessaires pour la suite ?
Car de ce fait, je me retrouve à l'heure actuelle dans l'incapacité de me connecter à epic games, et mon appli aussi

https://github.com/SkYNewZ/rest-fornite-api/pull/13

**Comment by qlaffont** [comment]
Yop SkynewZ,
Malheureusement non le système que j'utilise ne permet pas car il fait les mêmes requêtes que otn client.
Moi j'ai créé un compte dédié pour l'API et je n'ai aucun pb. Sinon c'est que tu rentres les mauvais token.
