### ISSUE TITLE
login does not posses ther permissions READ

### ISSUE THREAD

**Issue by rjp1996** [qlaffont/fortnite-api#30]
I followed all the instruction in the readme but i only get the message "Impossible to fetch user".
When i log the returned data i can get a errorCode/errorMessage and it states that my login does not posses the permission.

Am i doing something wrong or is there something else going on?

`{ StatusCodeError: 403 - {"errorCode":"errors.com.epicgames.common.missing_permission","errorMessage":"Sorry your login does not posses the permissions 'fortnite:stats:b2fd2f667852444d94dd735d69f6666e READ' needed to perform the requested operation","messageVars":["fortnite:stats:b2fd2f667852444d94dd735d69f6666e","READ"],"numericErrorCode":1023,"originatingService":"fortnite","intent":"prod-live" }`

**Comment by qlaffont** [comment]
Which function you have used ? 

This is strange your errors, i have never see this error before 🤔.

**Comment by rjp1996** [comment]
OK, for some reason it does work now, i did not edit a single line of code.

To answer your question in case you want to investigate: i tried checkPlayer and getStatsBR.

I modified this code in the checkPlayer method so it outputs the data
`.catch(() => {
    reject("Impossible to fetch User.");
});`
to
`.catch(() => {
    reject(data);
});`
