### ISSUE TITLE
Request package

### ISSUE THREAD

**Issue by wokkeltje** [qlaffont/fortnite-api#35]
Not sure if this is an local issue or in the package but:

I installed this npm package but when i run it it gives the error:

 The "request" library is not installed automatically anymore. install it with....

Even when i install that package and the request-promise as well i keep getting the error. Anyone has any idea?

Node version: v8.9.4

**Comment by qlaffont** [comment]
Hi @wokkeltje,
I have no internet actually (I move on new apartment x) at this time). End of the next week, i will have internet back. So remind me to checkup, on my Discord ;) https://discord.gg/PurBeRF
Regards
Quentin

**Comment by qlaffont** [comment]
Bug Fixed. Try to update.
