### ISSUE TITLE
Image library endpoint?

### ISSUE THREAD

**Issue by TheMaster** [qlaffont/fortnite-api#36]
Is there an endpoint or way to get image assets of characters. As the api has ids for pickaxes (3b829757-254d-4011-99d3-a4ab770af629) but can't work out how to identify that id to an image.

**Comment by qlaffont** [comment]
Hi @TheMaster,
I have no internet actually (I move on new apartment x) at this time). End of the next week, i will have internet back. So remind me to checkup how we can found assets about Fortnite, on my Discord ;) https://discord.gg/PurBeRF
Regards
Quentin

**Comment by modsognir** [comment]
The IDs are actually for that instance of the object (i.e. the user's particular copy of a Glider etc). Depending on the API the field you're looking for is usually called TemplateId, but it's not a 1-to-1 mapping to an asset. Some of them are close.

**Comment by TheMaster** [comment]
So how would I go about extracting assets? which contains the images Im looking for.
Thanks

**Comment by qlaffont** [comment]
@TheMaster & @modsognir if you have already have this informations you can add it to the repo (fork it and make a pull request ;))

**Comment by TheMaster** [comment]
I've been using a program called UModel for getting game assets

**Comment by savisaar2** [comment]
Hi dudes, 
I am very interested in this information. Fortnitetracker.com and such have the ability to pull store data with images, how would i be able to find a relationship between the store assets and the api call?
All i can find is displayAssetPath.

**Comment by savisaar2** [comment]
Can anyone link me to a pull archive of all shop assets

**Comment by leomelki** [comment]
How did you do please ?

**Comment by weeco** [comment]
@leomelki You have to decrypt the .pak files using AES. The hard part is to find the AES key, but someone usually shares the key with the community. You can use the UModel viewer to extract most of the assets. Read Gildor's forum for more information, everything is described there :)

**Comment by leomelki** [comment]
Thank you for the response. Indeed, I already did it but I don't know how to link the informations of the shop to the files we decrypted. I know that the id of the offer is virtual:/r5650hshlvak3otsblq62ui5c8[0]0#0
and the name id [VIRTUAL]1 x Stage Dive for 800 MtxCurrency but I can't find the linked texture, do you know how to find this ? Thank you !

**Comment by modsognir** [comment]
The id is a unique identifier for that occurance of the item in the store -
it won’t get you the image name. Those are stored in data table files.

**Comment by TheMaster** [comment]
This is kind of useless now as they have removed profile endpoint which gave you profile cosmetics
