### ISSUE TITLE
Does not posses the action \'PLAY\'

### ISSUE THREAD

**Issue by dkasabovn** [qlaffont/fortnite-api#41]
While attempting to use the fortnite api for a school project I have encountered the error code:
{ errorCode: 'errors.com.epicgames.common.missing_action',
        errorMessage: 'Login is banned or does not posses the action \'PLAY\' needed to perform the requested operation for platform \'\'',
        messageVars: [Object],
        numericErrorCode: 1023,
        originatingService: 'fortnite',
        intent: 'prod-live' } } }
Impossible to fetch User.
I can access the recent news and can confirm that my tokens and logins are correct but I cannot retrieve player data. I am using the .getStatsBR as seen in the documentation.
Any help would be appreciated!

**Comment by bloehle13** [comment]
I got this issue before. This is caused when the account you're using as login has not actually played a game before, and thus cannot retrieve stats. Play one game on that account and then run your code again. This should work.

**Comment by dkasabovn** [comment]
Ok that's weird because I have played over 70 hours of the game. But yes I
will try and get back to you if it works.

**Comment by bloehle13** [comment]
I suppose your issue could be the first part of the error: "Login is banned...", if you've played that much already.

**Comment by dkasabovn** [comment]
Maybe? I'm currently at school so once I get back I will try playing or
just registering a new account. But I'm pretty sure I'm not banned. I'll
see but thank you anyways for the help.

**Comment by dkasabovn** [comment]
Ok I came home and played a game of fORTNITE and confirmed that I wasn't
banned. Then I created a new account and played a game. I have tried
requesting stats but it gives me the same error code. Is there any other
information I should leave you?

**Comment by SkYNewZ** [comment]
I use this module too, can you test with your user here ? `https://api.fortnite.lemairepro.fr/v1/<plateform>/<username>`. If you always have this issue and what is the repsonse

**Comment by SkYNewZ** [comment]
After some testing with [Postman](https://www.getpostman.com/) I have successfully reproduce this error.
The EpicGames API use the autorization code flow, so like Quentin, you have to follow this procedure [(see the `login()` method)](https://github.com/qlaffont/fortnite-api/blob/master/index.js#L56).

1. Get one token with your email and password
2. Get one code with the response `access_token`
3. Get a new `access_token` with the response code

Finally with this last `access_token`, you can access to all availables endpoints.
[Here a Postman collection for using the EpicGames API](https://www.getpostman.com/collections/c3de2367724268d3305f)
