### ISSUE TITLE
Unhandled promise rejections

### ISSUE THREAD

**Issue by SkYNewZ** [qlaffont/fortnite-api#42]
When my token is too used (when consecutively testing for example), I obtain this error but the process don't exit...
Can you test the valid access token before start using this ? https://github.com/qlaffont/fortnite-api/blob/master/index.js#L51

```(node:17) UnhandledPromiseRejectionWarning: Please enter good token
(node:17) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.```

**Comment by ItsCEED** [comment]
Simple solution for this is to add multi acc support by yourself, wont be that hard.

**Comment by SkYNewZ** [comment]
Sorry, can you explain "add multi acc support", i don't understand :confused:

**Comment by qlaffont** [comment]
I will add the catch block no problem. But actually on stats-fortnite.com, I use only one account/session and it's work very well !

**Comment by SkYNewZ** [comment]
Yes i agree and understand. But because I testing my api, when I test consecutively, the `login()` method ask a new bearer token that create a new session on Epic Games servers.
So when this case arrived, even launching my epic games launcher in order to play, it's impossible because I if this this error : "too many session, please disconect". If you don't need to kill session, what do you think about provide a `getToken()` method ? I could kill my session (with the current access_token), at the end of my test and avoid "too many session" because in this case a will have one 1 session for the production env, 1 forthe developement env and "temporary" session for token
