### ISSUE TITLE
If a kill session method is usefull ?

### ISSUE THREAD

**Issue by SkYNewZ** [qlaffont/fortnite-api#43]
I found the kill session endpoints, maybe it can be usefull:
```bash
curl -X DELETE \
  'https://account-public-service-prod03.ol.epicgames.com/account/api/oauth/sessions/kill/{{ACCESS_TOKEN}}' \
  -H 'Authorization: Bearer {{ACCESS_TOKEN}}'
```
It can be usefull for kill the current session at the end of testing to prevent error "too many session"

**Comment by qlaffont** [comment]
Why it's usefull ? Logically, you just need a session for your account.
For Stats-Fortnite.com, i have only one session and it's working well !

**Comment by SkYNewZ** [comment]
https://github.com/qlaffont/fortnite-api/issues/42

**Comment by qlaffont** [comment]
#57
