### ISSUE TITLE
new QueryProfile endpoint

### ISSUE THREAD

**Issue by andrewtian** [qlaffont/fortnite-api#44]
It seems epic has changed the QueryProfile endpoint, anyone know what the new one is supposed to be? I do not have a computer right now to do scraping. My sites are not working.

🙂

**Comment by qlaffont** [comment]
@andrewtian, yes i confirmed ! I will work on it if I have time this week or next week.

**Comment by ItsCEED** [comment]
@qlaffont you can post a small tutorial on how to do this so we can do this and scrape and update when you are not avalible

**Comment by TheMaster** [comment]
Why was this closed? This is still an issue or am I missing something

**Comment by qlaffont** [comment]
There is not new endpoint. It still the same. It's just Epic Games cut stats during some time.

**Comment by ItsCEED** [comment]
@TheMaster there must be other way they are pulling data, most of the websites are running with no issue even after the endpoint got closed.

@qlaffont also, do you know the match endpoint?

**Comment by qlaffont** [comment]
Stats-Fortnite.com use this API and i have no issue and i use the same endpoint x). Try to reboot your program, you probably need to renew the token.

**Comment by SkYNewZ** [comment]
Your API is doing this, so you can test by yourself
```
curl -X POST \
  'https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{{accountId}}/public/QueryProfile?profileId=profile0&rvn=-1' \
  -H 'Authorization: Bearer f725da71467a4e29b190d8eefc547a0e' \
```
return
```json
{
    "errorCode": "errors.com.epicgames.modules.profiles.operation_forbidden",
    "errorMessage": "Operation QueryProfile not allowed via this route",
    "messageVars": [
        "QueryProfile"
    ],
    "numericErrorCode": 12813,
    "originatingService": "fortnite",
    "intent": "prod-live"
}
```

**Comment by TheMaster** [comment]
so tried the above. With new access token still get the same response operation_forbidden. note this was working a few days ago.

**Comment by TheMaster** [comment]
I guess i will check if a new endpoint exist later when I'm back at my computer.

**Comment by TheMaster** [comment]
just looked using fiddler and I can get the data using https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{{accountId}}/**client**/QueryProfile?profileId=athena&rvn=-1

however when i try to get that data through postman i get **invalid_payload**

**Comment by ItsCEED** [comment]
@qlaffont

**Comment by TheMaster** [comment]
I don't think Stats-Fortnite.com is using 'https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/game/v2/profile/{{accountId}}/public/QueryProfile?profileId=athena&rvn=-1' endpoint. Just seems to pull stats which is different endpoint. I need the user profile endpoint which contains character item ids etc

**Comment by qlaffont-smiirl** [comment]
Guys, i'm busy this week so i will anwser all issues next week. Stats-Fortnite.com use this API with all endpoint !

**Comment by qlaffont** [comment]
Guys, i'm busy this week so i will answer all issues next week. Stats-Fortnite.com use this API with all endpoint !

**Comment by weeco** [comment]
@TheMaster That's not possible. You can only access this endpoint for your own account. The server checks the access and returns 403 if you try it for other profiles.

**Comment by TheMaster** [comment]
Yeah I understand that now. I wished Epic games made that data public like it used to be. 😞

**Comment by Maiu15** [comment]
It is public, a lot of people do it.

**Comment by SkYNewZ** [comment]
I create an API if you want to try it : [fortnite-api](https://github.com/SkYNewZ/fortnite-api) an a demo is setup [here](https://fortnite.lemairepro.fr/api/docs/)

**Comment by TheMaster** [comment]
To my original problem 9 months ago. I wanted to access user locker data. As that used to be included when using query profile endpoint. That data is no longer returned by the endpoint.

**Comment by Maiu15** [comment]
But there should be another endpoint then? How does all the other people do it?

**Comment by TheMaster** [comment]
As far as im aware no one can get that data. Other people can only get game
stats. Not locker data
