### ISSUE TITLE
Passing in usernames with spaces?

### ISSUE THREAD

**Issue by mrmikeman2** [qlaffont/fortnite-api#56]
Having some issues with users that have Epic Games usernames that contain spaces. I can send in the name of the user with the space, but it always returns user not found. Not sure if I'm doing something wrong or if the API isn't capable of handling spaces in usernames.

**Comment by mrmikeman2** [comment]
Well shoot, I figured out the problem on my own, and it wasn't related to any of this. Thanks for the reply regardless!

**Comment by Apollyon365** [comment]
I actually have a problem with this too, anyone knows the solution?
