### ISSUE TITLE
Get the new replay list data

### ISSUE THREAD

**Issue by tcarlsen** [qlaffont/fortnite-api#60]
With the newest update Epic added replayed. I pretty sure the replays themself only can be viewed inside the client.

But the replays have som nice stats with them (win / kills and stuff)

**Comment by TheMaster** [comment]
I will have look later tonight. Check if any new endpoints exist for this

**Comment by qlaffont** [comment]
I will check it this WE. If you or @TheMaster, have the new endpoint you can create a pull request. I will add it ;).

**Comment by TheMaster** [comment]
Sure I'm at work at the moment so i can't do it now. Will try and check later today.

**Comment by TheMaster** [comment]
Just had a quick look for new endpoints for stats/replays. Couldn't find anything new or useful :(

**Comment by weeco** [comment]
Replay data is collected while playing and stored locally.

**Comment by qlaffont** [comment]
Store Locally, impossible to get replay from other account so issue closed.
