### ISSUE TITLE
getStatsPVE no longer working?

### ISSUE THREAD

**Issue by jryd** [qlaffont/fortnite-api#62]
I was trying to debug why calls to getStatsPVE weren't working and when I make the request, here is the response I get:

```
{  
   "errorCode":"errors.com.epicgames.modules.profiles.operation_forbidden",
   "errorMessage":"Operation QueryProfile not allowed via this route",
   "messageVars":[  
      "QueryProfile"
   ],
   "numericErrorCode":12813,
   "originatingService":"fortnite",
   "intent":"prod-live"
}
```

Is this method no longer working, or is there a different reason I am getting this message?

**Comment by jryd** [comment]
This may be linked to a comment @TheMaster on another issue where access to QueryProfile has been removed...

**Comment by qlaffont** [comment]
Remove on 2.9.0 #63
