### ISSUE TITLE
Incorrect token type

### ISSUE THREAD

**Issue by henhouse** [qlaffont/fortnite-api#64]
Hi again,

I was working on an endpoint for leaderboards and noticed that I needed JWT token with permissions inside in order to make those requests... I began looking through Fiddler and saw that the token request (`token_type`) type must be "eg1" in order for us to get this seemingly-JWT looking token back. I wonder if the request [here](https://github.com/qlaffont/fortnite-api/blob/master/index.js#L114) is wrong and not "egl"?

We get back a basic access token there, but if you request "eg1" as in the number 1, not the letter L, you get a JWT token back instead. This token is needed for other permissive requests, such as requesting data from the new leaderboard APIs.

Was curious if you had any additional information on this, or if it is a typo?

The initial request to `/account/api/oauth/token` is an encoded body which reads:
`grant_type=client_credentials&token_type=eg1`

**Comment by qlaffont** [comment]
Hi,
Is not the typo ! It's "egl" But if you want you can make a fork to check if with eg1 it will be better. When I created the API, they have use eg1 parameters maybe they have change since the beginning ^^.
Keep me informed ;)

**Comment by henhouse** [comment]
I believe this to be a typo, still. Using Fiddler 4 I can only see requests always using "eg1" instead of egl. "egl" doesn't appear to do anything on the request. See screenshot examples below:

Request using `elg` returns small access token:
![image](https://user-images.githubusercontent.com/30731/38770329-a3233190-4011-11e8-88ac-c0e7af21c28b.png)

Changing it to anything else generate the _same_ small token:
![image](https://user-images.githubusercontent.com/30731/38770337-b91ee250-4011-11e8-9a8c-4771170fc421.png)

However, if we request `eg1` we get a large JWT token back:
![image](https://user-images.githubusercontent.com/30731/38770341-cc51dce2-4011-11e8-9b2c-e5adc814c15f.png)

**Comment by henhouse** [comment]
Regardless, the small access token still works for most API calls. I only encountered 401 Unauthorized errors when I did not have this large, JWT token when attempting to interface the [leaderboard API](https://github.com/henhouse/fortnite-go/blob/master/epic.go#L22). This JWT token is needed instead of the small one in order to access those endpoints.

**Comment by qlaffont** [comment]
So we need to change our authentification method ? Did you get much thing with this method ?
