### ISSUE TITLE
LeaderBoards endpoint 

### ISSUE THREAD

**Issue by ibrahim-abde** [qlaffont/fortnite-api#65]
is there any leaderboards endpoint ?

I searched and found this 3 endpoints :
https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/leaderboards/type/group/stat/br_score_pc_m0_p9/window/weekly?ownertype=1

https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/leaderboards/type/global/stat/br_placetop1_pc_m0_p9/window/weekly?ownertype=1&pageNumber=0&itemsPerPage=50

https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/leaderboards/type/group/stat/br_placetop3_pc_m0_p9/window/weekly?ownertype=1

I don't think those are for the global leaderboard.

**Comment by henhouse** [comment]
Nice job!

**Comment by qlaffont** [comment]
#67
