### ISSUE TITLE
How do you discover the endpoint urls when they're transmitted via https?

### ISSUE THREAD

**Issue by jnguyen32** [qlaffont/fortnite-api#69]
Hello,

Great work. Just curious how you're able to discover the endpoint URL's that you have so far? I assume using something like wireshark would show the server domain but not the actual endpoint due to HTTPS?

**Comment by TheMaster** [comment]
I use a tool called fiddler 4

**Comment by modsognir** [comment]
Tools like Fiddler and Charles both let you "man in the middle" yourself, allowing you to see HTTPS transmitted content.

**Comment by jnguyen32** [comment]
Thanks, do you know how websites like fortnitemaster.com are able to get match history and metadata/stats related to it? Using fiddler, I'm not seeing any reference to an endpoint that has this type of information.

**Comment by TheMaster** [comment]
Match history by them sites are worked out by matches played, kills,etc no endpoint for this
