### ISSUE TITLE
How can i get tokens?

### ISSUE THREAD

**Issue by JustCarry** [qlaffont/fortnite-api#74]
I really didn't understand about how can i get tokens,

I'm stick on Epic game launcher step..

I launch it then i did go to fiddler, and trying to find  /account/api/oauth/token request and i didn't found it!

please help me at this step..

**Comment by JustCarry** [comment]
i cannot find /account/api/oauth/token in launcher

**Comment by savisaar2** [comment]
Tools->Options->HTTPS->Decrypt HTTPS checked?

**Comment by JustCarry** [comment]
nope

**Comment by savisaar2** [comment]
Okay make sure that is checked then you should be able to find the packet

**Comment by KindaIntellectual** [comment]
Doesn't seem to work with auto login. After I launched Fiddler, and then the Epic launcher, I signed out (of Epic) and then signed back in and found the token in fiddler.

**Comment by jeffreyhorner** [comment]
@KindaIntellectual I tried your solution of signing out (via the launcher) and back in and it didn't work for me. As soon as I turn off Fiddler HTTPS decryption, I'm able to launch the game without having to sign in.

**Comment by qlaffont** [comment]
I have make some test and i'm agree Fortnite have blocked Fiddler in Game starting process. We need an another way to found the second token 🤔

**Comment by qlaffont** [comment]
Okay i found it : 
- Install & Open Fiddler 4
- In Tools -> Options -> HTTPS, Select Capture HTTPS Connects
- After that start your epic games launcher.
- You will see a request with /account/api/oauth/token. Click on it and click after that on Inspectors get the header (Authorization header content and remove basic) => This header is your Client Launcher Token
- Press F12 to stop scan (Fortnite stop working if you can at this moment)
- Launch Fortnite
- When the game tell you : "Connecting" or "Update" in waiting screen, Press F12 to reactivate requests capture
- You will see again a request with /account/api/oauth/token. Click on it and click after that on Inspectors get the header (Authorization header content and remove basic) => This header is your Fortnite Client Token

Can you confirm this, for me it's working.

**Comment by qlaffont** [comment]
I have edited my message @Tntcommando1 and @jeffreyhorner you need to do the exact process described before.

**Comment by jeffreyhorner** [comment]
Sorry, still doesn't work for me.

**Comment by himanmenGit** [comment]
Not working process.
Can you take a video?

**Comment by qlaffont** [comment]
I don't have time to do it. But the exact process is working. If you don't respect, precisely the process is not working.

**Comment by himanmenGit** [comment]
Ok. Thank you. I'll keep trying.

**Comment by da772** [comment]
@qlaffont 's workaround also didn't work for me.

I had to get the Client Auth Token through the Fortnite iOS app:

**Computer Steps**
-Install & Open Fiddler 4 on computer
-In Tools -> Options -> HTTPS, Select Capture HTTPS Connects -> Decrypt HTTPS traffic -> ...from remote clients only
-In Tools -> Options -> Connections(take note of fiddler port) -> Select - Allow remote computers to connect
-Allow fiddler to connect through windows firewall (inbound/outbound)
-Find computer's local ip (Windows: type /ipconfig in command prompt)

**iOS Steps**
-Connect to the same network as the computer with fiddler
-go to Settings -> Wi-Fi -> (your wifi name) press the (i) next to it
-scroll down to Configure Proxy -> Manual -> Server: (type computers local ip address) | Port: fiddler's port (default is 8888) | do NOT enable authentication -> save (top right)
-in iOS browser go to this website http://ipv4.fiddler:8888 (replace 8888 with fiddler's port)(type it out fully!)
-click on the hyper link that reads: You can download the FiddlerRoot certificate
-install certificate, press done
-go to Settings -> General -> About-> Certificate Trust Settings (at the bottom) -> enable full trust for DO_NOT_TRUST_FiddleRoot
-Make sure Fiddler on computer is capturing.
-Open Fortnite app and login (relog if already logged in)
-On computer Fiddler should now have  /account/api/oauth/token (This is your Client Token)

[Fiddler iOS documentation](https://docs.telerik.com/fiddler/Configure-Fiddler/Tasks/ConfigureForiOS)

**Comment by qlaffont** [comment]
@da772 my procedure is only for Fortnite on PC. 

@bpar476 capture all requests (not a specified window) after that you just need to do the procedure and after that you can found oauth request with a CTRL + F

**Comment by bpar476** [comment]
@qlaffont Sorry I wasn't clear, when I said window I meant window of time as in, disabling and re-enabling didn't work for me, poor language on my part. Perhaps there is a difference in behaviour depending on the server. I am connecting to the OCE servers.

When I turn on capture and the game is saying "Logging into Epic Services" I would expect there to be some traffic picked up in Fiddler but there is nothing at all. I think that the procedure you've described doesn't work in all cases. Unless I'm doing something wrong.

**Comment by qlaffont** [comment]
@bpar476 you need to turn on when loading screen change to login screen.

**Comment by bpar476** [comment]
@qlaffont I just tried again, enabling capture as soon as the loading screen transitions to the logging in/connecting screen. No Fortnite traffic in Fiddler at all during that time. I have HTTPS Connect enabled and I have decrypt HTTPS traffic enabled also.

**Comment by eshao731** [comment]
I tried it many times, but I couldn't get Fortnite token till now.

**Comment by DylanMcGee** [comment]
@eshao731 what did you do differently to get the Fortnite token?

**Comment by eshao731** [comment]
@DylanMcGee @bpar476 Are you sure you can get the Fortnite token now?
**Can Fortnite  login with Fiddler open?**

**Comment by bpar476** [comment]
No, I still can’t get the token. The way you worded your comment it seemed like you were able to get the token.

**Comment by DylanMcGee** [comment]
@bpar476 @eshao731 

I looked into the documentation for the PHP api and they have a shared token.  I'm not sure if there is a limit to how many calls you can do with this, but I was able to run a few hundred calls without issue.

3rd parameter (epic games launcher token) : "MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y="	

4th parameter (fortnite token)
: "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="

**Comment by eshao731** [comment]
@DylanMcGee Thank you for your answer. I've just finished reading the PHP api .The code is valid.

**Comment by qlaffont** [comment]
@DylanMcGee & @eshao731, they share their token. I didn't share my tokens because it's a security issue and if Epic Games want to cancel my token i need to renew it and modify the token on my fortnite-api.

**Comment by qlaffont** [comment]
You can check the new Readme.Md on Master Branch. The Readme.md was updated.

**Comment by eshao731** [comment]
@qlaffont Their launcher token is the same as the token I get,Isn't their fortnite token same as yours?

**Comment by qlaffont** [comment]
It's seems that I have the same Launcher/Fortnite Token. So you can use it, but i will not edit my code because if they change it I want to be sure that every developers can change it easily.

**Comment by eshao731** [comment]
Thank you for your answer!

**Comment by qlaffont** [comment]
No problem ^^. I consider this issue close.

You can use the dedicated procedure in Readme.md or you can use this token (They can change any time) : 

3rd parameter (epic games launcher token) : "MzRhMDJjZjhmNDQxNGUyOWIxNTkyMTg3NmRhMzZmOWE6ZGFhZmJjY2M3Mzc3NDUwMzlkZmZlNTNkOTRmYzc2Y2Y="

4th parameter (fortnite token)
: "ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ="

**Comment by bpar476** [comment]
Great work troubleshooting this issue guys. I look forward to seeing what I can do with this sweet api 😁

**Comment by CapnS** [comment]
The shared token no longer works and throws an error. I tried with 2 different apis and it doesn't work. Any chance we could get another one to share if someone is willing to be nice?

**Comment by Fyb3roptik** [comment]
Looks like these credentials have been hosed. Getting an error from EPIC that the token is not valid

**Comment by NationReturns** [comment]
Fortnite just released a new api update, issue retrieving new auth token.

**Comment by 1337Turbo** [comment]
Anyone got the new fortnite api bearer key?

**Comment by juanpablofortnite** [comment]
I have this php code to see the store, do you think having the token would work? 
https://i.imgur.com/CAdaoO8.png

**Comment by DanyIonut2580** [comment]
hey anyone ?

**Comment by DanyIonut2580** [comment]
?

**Comment by DanyIonut2580** [comment]
i need help with token

**Comment by Fyb3roptik** [comment]
Launcher Token
```
MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE=
```

Game Token
```
ZWM2ODRiOGM2ODdmNDc5ZmFkZWEzY2IyYWQ4M2Y1YzY6ZTFmMzFjMjExZjI4NDEzMTg2MjYyZDM3YTEzZmM4NGQ=
```

**Comment by DanyIonut2580** [comment]
i need the new api fortnite (Launcher Token)

**Comment by DanyIonut2580** [comment]
please!

**Comment by DanyIonut2580** [comment]
is not api , epic games has been changed

**Comment by DanyIonut2580** [comment]
is my discord JohnW#3117 tell me

**Comment by Firebelias12** [comment]
Join the group, everthing you need is there.
https://discordapp.com/invite/Gdvbgpq

**Comment by DanyIonut2580** [comment]
is expired

**Comment by Firebelias12** [comment]
Oh well, here's the complete auth-flow (fortnite-access-token)https://gist.github.com/Terbau/9a07849fb30c0232af730265c327e27c

**Comment by DanyIonut2580** [comment]
MzQ0NmNkNzI2OTRjNGE0NDg1ZDgxYjc3YWRiYjIxNDE6OTIwOWQ0YTVlMjVhNDU3ZmI5YjA3NDg5ZDMxM2I0MWE is not work

**Comment by Firebelias12** [comment]
I just tested it and the program works just fine.

**Comment by DanyIonut2580** [comment]
No wtf, send me your discord

**Comment by DanyIonut2580** [comment]
Hey , it s api has been changed

**Comment by Fyb3roptik** [comment]
API works fine

**Comment by DanyIonut2580** [comment]
how 
?

**Comment by DanyIonut2580** [comment]
You have discord?

**Comment by DanyIonut2580** [comment]
if you have , add me

**Comment by DanyIonut2580** [comment]
JohnW#3117

**Comment by DanyIonut2580** [comment]
give me your discord

**Comment by Fyb3roptik** [comment]
Just sent you a FR. From Fyb3roptik

**Comment by DanyIonut2580** [comment]
Done  check your discord

**Comment by DanyIonut2580** [comment]
please
