### ISSUE TITLE
I can get the Launcher token, but Fortnite will not login with Fiddler open. Is there a fix?

### ISSUE THREAD

**Issue by eshao731** [qlaffont/fortnite-api#79]
When I open Fiddler 4, start fortnite will not connect to the server!
I can get the Launcher token!

how to slove it ??

- Install & Open Fiddler 4
- In Tools -> Options -> HTTPS, Select Capture HTTPS Connects
- Start Capture
- After that start your epic games launcher.
- You will see a request with /account/api/oauth/token. Click on it and click after that on Inspectors get the header (Authorization header content and remove basic) => This header is your Client Launcher Token
- Press F12 to stop scan (Fortnite stop working if you capture HTTPS requests at this moment)
- Launch Fortnite
- When the game tell you : "Connecting" or "Update" in waiting screen, Press F12 to reactivate requests capture
- You will see again a request with /account/api/oauth/token. Click on it and click after that on Inspectors get the header (Authorization header content and remove basic) => This header is your Fortnite Client Token
- Stop Capture

**When the game tell you : "Connecting" or "Update" in waiting screen, Press F12 to reactivate requests capture**

I tried it many times. It do not work!!!

**Comment by qlaffont** [comment]
#74
