### ISSUE TITLE
Question à propos de l'API FORTNITE

### ISSUE THREAD

**Issue by Valor147** [qlaffont/fortnite-api#80]
Bonjour, nous avons pour objectif de créer un site communautaire sur Fortnite pour cela nous aurions donc besoin de faire notre API, nous aimerions donc savoir si il était légal de créer une API de Fortnite exactement comme vous l'avez fait, c'est à dire en se servant directement des liens provenant d'EPIC GAMES comme décrit dans votre API : 

https://github.com/qlaffont/fortnite-api/blob/master/tools/endpoint.js

Cordialement,

**Comment by qlaffont** [comment]
L'API utilise les mêmes endpoint que le jeu en lui même. De ce fait, tout est légal dans son utilisation. De plus, je suis l'un des fondateurs de Fortnite France et on est en contact perpétuelle avec Epic Games. Donc il n'y aucun souci pour utiliser l'API.

**Comment by XeraFiuYTB** [comment]
Bonjour @qlaffont , pourriez vous faire en sorte qu'avec l'API nous puissons connaitre le code créateur d'une personne, explication, nous aimerions faire des Statistiques dans le serveur Discord et mettre un grade "Fidèle" aux personnes qui ont mi notre Code Créateur, cordialement XeraFiu

**Comment by qlaffont** [comment]
Malheureusement je ne fais plus de recherche sur l'APIs Fortnite. Cependant si vous avez le moyen de récupérer cette requête par une autre librairie, je peux l'intégrer sur celle là.

**Comment by XeraFiuYTB** [comment]
Ok, je vous préviendrais merci
