### ISSUE TITLE
Windowed BR Stats

### ISSUE THREAD

**Issue by jeffreyhorner** [qlaffont/fortnite-api#83]
I noticed here:

```
    statsBR: accountId => {
        return (
            "https://fortnite-public-service-prod11.ol.epicgames.com/fortnite/api/stats/accountId/" +
            accountId +
            "/bulk/window/alltime"
        );
    }
```

the **window** key word found in the API endpoint.

Any known alternatives to this other than **alltime**?

I'm searching for ways of gathering placements for matches played within a window of time for a set of players.

**Comment by weeco** [comment]
Yeah, I've created an enum for this in my lib, see:

https://github.com/weeco/fortnite-client/blob/develop/src/enums/time-window.enum.ts

**Comment by maciejbuchert** [comment]
I have one more
`/window/daily`
but errorMessage is `Stat name list cannot be null or empty.`

@weeco How to use /monthly ?

**Comment by weeco** [comment]
@maciejbuchert They don't allow all time windows for all routes, but weekly is for example used for the leaderboards. One could probably guess there are further timewindows like "yearly". One would just need to figure out what TimeWindows are valid for each route.

**Comment by kinsi55** [comment]
I know this is kinda unrelated, but is it known how Fortnitetracker is able to fetch the BR skins used by a player?

**Comment by TheMaster** [comment]
They are not anymore as epic removed the profile query endpoint

**Comment by savisaar2** [comment]
Yes you datamine that info which is how they have it and how i do it.

**Comment by TheMaster** [comment]
But you can't match those skins to a profile anymore. Or is there another way of doing it. Haven't looked in a couple of weeks

**Comment by savisaar2** [comment]
Ah i get what you mean well it will depend wgat the profile api returns i
havent coded that part yet but will investigate later date.

**Comment by TheMaster** [comment]
They disabled that endpoint. Thats why fortnitetracker doesn't show profile skins

**Comment by kinsi55** [comment]
> They are not anymore as epic removed the profile query endpoint

Seems like you might be right, my bad. I didnt realize the skins arent listed on the profile anymore, they are still listed in the leaderboard but I guess that is outdated data. Its unfortunate that epic doesnt have a public API.

**Comment by JaydenMaalouf** [comment]
There are two current API endpoints
/bulk/window/alltime
/bulk/window/weekly

Don't mind the name. Weekly is actually seasonal data.

**Comment by maciejbuchert** [comment]
Daaamn. Weekly is seasonal data? rly? so funny 😆

**Comment by JaydenMaalouf** [comment]
Yes. http://coreoce.com/fortnitebr has been using it for our LlamaBot since literally the dawn of this API haha

**Comment by maciejbuchert** [comment]
@JaydenMaalouf any idea how Fortnite Scout obtains session data ?

**Comment by JaydenMaalouf** [comment]
@maciejbuchert Same way that FNTracker does. People stay on the site, the client will trigger a refresh of the stats. Compare stats with previous version. Work out the difference, if you only have 1 matches played difference then you have 1 matches results, otherwise you will need to group it into x amount of matches

**Comment by JaydenMaalouf** [comment]
It's purely based on having users use and refresh their page

**Comment by maciejbuchert** [comment]
I thought so

**Comment by JaydenMaalouf** [comment]
Feel free to chat to me about API shiz for Fortnite
Kanga#8041 is my Discord

**Comment by qlaffont** [comment]
Sorry Guys, some busy weeks ^^. I will try to review the PR next week or this week ^^.

**Comment by qlaffont** [comment]
#89
