### ISSUE TITLE
Challenges data

### ISSUE THREAD

**Issue by savisaar2** [qlaffont/fortnite-api#85]
Does this api list ALL available endpoints? Is there currently any endpoint which holds Battlepass week data eg: Challenges by week.

**Comment by kinsi55** [comment]
These are the known endpoints, theres surely other ones but apparently Epic decided to enable certificate pinning in the latest Fortnite update, hence its not possible to look around for other ones anymore.

**Comment by savisaar2** [comment]
Do you think sites pull Challenges from an endpoint(no evidence from any api on github) or by entering it manually?

**Comment by JaydenMaalouf** [comment]
The Challenges are in game files. Not an API Endpoint. It's all included in your cloud save so being able to get the data out from that, would be difficult.

**Comment by savisaar2** [comment]
I am sure fortnitetracker doed it automatically whether its api or umodel i just cant find any info anywhere

**Comment by JaydenMaalouf** [comment]
It's manual data mining. I'm in the process of writing an automated thing for it, though.

**Comment by JaydenMaalouf** [comment]
Posted this in the Discord
But I'm making good progress on the Data extraction tool. Working well!
https://cdn.discordapp.com/attachments/392667296822198279/448923803599503362/rec20.gif

I have all ingame items: names, descriptions and preview images. As well as Challenges: names and descriptions

Going to add the ability to scrape the data values (ie. rarity, challenge count etc)

**Comment by savisaar2** [comment]
I think it would be a nice addition to the script if you haven't already to
allow a covert to png or something :)

**Comment by monkeydioude** [comment]
@JaydenMaalouf did you make progress on the extraction tool ? I'd be glad to help if needed

**Comment by ericlewis** [comment]
this PR may be of help: https://github.com/qlaffont/fortnite-api/pull/126. I don't really have all challenge data, it's manually added. Would love to see your extraction tool @savisaar2 :)

**Comment by JaydenMaalouf** [comment]
I haven't worked on it since May so it may need be upto date with the current version of Fortnite. However, I can take a look over the coming weekend.

**Comment by ericlewis** [comment]
Let me know, I’m happy to help with it if the code is posted somewhere.

**Comment by JaydenMaalouf** [comment]
I will create a repo when I'm home next. Currently in the office.

**Comment by ericlewis** [comment]
@JaydenMaalouf I figured out how to get the value's for challenges, but could use help figuring out how to get their names

**Comment by RythenGlyth** [comment]
> Posted this in the Discord
> But I'm making good progress on the Data extraction tool. Working well!
> https://cdn.discordapp.com/attachments/392667296822198279/448923803599503362/rec20.gif
> 
> I have all ingame items: names, descriptions and preview images. As well as Challenges: names and descriptions
> 
> Going to add the ability to scrape the data values (ie. rarity, challenge count etc)

Can you give me your code

**Comment by jatuttle** [comment]
I know this is an old post but I'm curious if anyone has been able to get challege completion status? Fortniteapi.com has a legit challenge endpoint
Challenges

GET Challenges
https://fortnite-api.theapinetwork.com/challenges/get?season=current
HEADERS
Authorization{{authorization}}
PARAMS
seasoncurrent

Example Request
Challenges
curl --location --request GET "https://fortnite-api.theapinetwork.com/challenges/get?season=current" \
  --header "Authorization: {{authorization}}"

Just create an account and to get your authorization code and replace {{x}} with your code --> returns
