### ISSUE TITLE
Error processing

### ISSUE THREAD

**Issue by Friday14** [qlaffont/fortnite-api#86]
At this point, I caught the error associated with throttling. The error message is not obvious, it seems to me that we should return err.message

https://github.com/qlaffont/fortnite-api/blob/c5a063733dbacaa49c86c26113cafc68f86ed2fe/index.js#L134

**Comment by qlaffont** [comment]
Can you tell me how do you have throttling, i will try to reproduce the error.

**Comment by Friday14** [comment]
send many, many requests with the wrong token

**Comment by Friday14** [comment]
{ StatusCodeError: 429 - {"errorCode":"errors.com.epicgames.common.throttled","errorMessage":"Operation access is limited by throttling policy, please try again in 221 second(s).","messageVars":["221"],"numericErrorCode":1041,"originatingService":"com.epicgames.account.public","intent":"prod"}
