### ISSUE TITLE
Cant get my Launcher token

### ISSUE THREAD

**Issue by EliteDaMyth** [qlaffont/fortnite-api#92]
Everything is on and i followed the exact steps but there isnt any request to  /account/api/oauth/token

**Comment by EliteDaMyth** [comment]
also the launcher works perfectly itt log ins normally :P

**Comment by EliteDaMyth** [comment]
do i have to install the npm package first?

**Comment by qlaffont** [comment]
Check the Readme.MD. To get tokens you don't need to have npm package install first. You need it to execute your code.
