### ISSUE TITLE
No 2nd oauth token

### ISSUE THREAD

**Issue by RayzonDE** [qlaffont/fortnite-api#93]
There is no second /account/api/oauth/token request if I capture the traffic at the update or login screen....

**Comment by qlaffont** [comment]
#92

**Comment by RayzonDE** [comment]
Bro I tried it 100 times... after I start Fortnite there is an /account/api/oauth/exchange request but no more token if I capture traffic in the loading screen. I recorded it for you it's only 1 minute https://www.youtube.com/watch?v=nHBqp-IusyA what am I doing wrong?
