### ISSUE TITLE
No Fortnite client token

### ISSUE THREAD

**Issue by RayzonDE** [qlaffont/fortnite-api#94]
Bro I tried it 100 times... after I start Fortnite there is a /account/api/oauth/exchange request but no more token, if I capture traffic in the loading screen. I recorded it for you it's only 1 minute https://www.youtube.com/watch?v=nHBqp-IusyA what am I doing wrong?

**Comment by NickSuperb** [comment]
@monkeydioude Can you link to this PHP api?

**Comment by RayzonDE** [comment]
@NickSuperb I think I found the API https://github.com/Tustin/fortnite-php

**Comment by jeffreyhorner** [comment]
The issue is that your Fortnite game won't verify Fiddler's certificates since it's using libcurl with verifypeer=true by default.

You can override this by adding the command line option -HTTP=WinInet in the Launcher (click the gear icon), and make your computer trust the Fiddler root certificate.

**Comment by weeco** [comment]
@jeffreyhorner Apparently they have fixed this loophole, did you find another possibility to bypass the SSL pinning?

**Comment by jeffreyhorner** [comment]
No I haven't scoped out this issue in awhile.
