### ISSUE TITLE
Expose access tokens

### ISSUE THREAD

**Issue by SirWaddles** [qlaffont/fortnite-api#97]
I'm writing some code that interfaces with the Updates/Launcher part of the Epic system, I was wondering if you could just add a quick method that exposes the token that's [retrieved on this line.](https://github.com/qlaffont/fortnite-api/blob/master/index.js#L91)

It gets replaced later on, so I can't just use `.access_token`

I can write a PR if you like, but I'm not sure how you would want this done (if at all.)

**Comment by qlaffont** [comment]
When you call the FortniteAPI you can have the token with : FortniteApi.access_token .
So it will not be on the API.

**Comment by SirWaddles** [comment]
As far as I understand it, there's a separate token for the Fortnite API as there is for the Launcher API. The token I'm after is the first one, but it's only temporarily stored on the FortniteApi object. It gets replaced by the token retrieved using the "FORTINTE CLIENT TOKEN" authentication.
