### ISSUE TITLE
Impossible de rechercher plusieurs utilisateurs à la fois ?

### ISSUE THREAD

**Issue by Valoroeckoi** [qlaffont/fortnite-api#98]
Bonjour, j'aimerais savoir si il y a une possibilité de rechercher plusieurs personnes simultanément à l'aide des pseudos utilisateurs ou des identifiants  ?

Par exemple pour récupérer 500 utilisateurs à la fois en une seule requête, sans être obliger de les rechercher un par un.

PS : Au bout d'une centaine le serveur nous retourne une erreur "UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 92): Please enter good token"

Cordialement, Valor

**Comment by monkeydioude** [comment]
Hello,

Non ce n'est pas possible. Je n'ai jamais eu l'erreur mentionné. Je n'utilise pas cette lib en JS, mais je n'ai jamais eu ce probleme avec mon implem et mes services tournent toute la journée. 

Par contre je requete jamais autant de personnes en peu de temps, en séquentiel. Tout est en asynchrone et séparé dans le temps.

T'es sur que l'erreur vient de là et pas d'un token qui a expiré entre temps ?

**Comment by Valoroeckoi** [comment]
Merci de ta réponse,

Actuellement nous voulions faire des tests donc j'ai utilisé un "Fortnite Client Token" qui était disponible sur un forum car notre problème numéro 1 est que nous n'arrivons pas à obtenir notre  "Fortnite Client Token", pour le "Client Launcher Token" aucun soucis avec fiddler, mais par contre pour le "Fortnite Client Token" nous avons essayé énormément de fois, étape par étape exactement comme expliqué dans le readme, mais impossible d'obtenir ce token. D'après les issues que j'ai vu il me semble que nous ne sommes pas les seuls à avoir ce problème de token fortnite introuvable. Donc en premier lieu si quelqu'un a une solution à ce problème ça serait sympa ;)

**Comment by monkeydioude** [comment]
#94
